{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Helper Functions \n",
    "(Run hidden cell)\n",
    "- Training Accuracy and Loss Graphs:    plot_history(history)\n",
    "- Predictions:                          print_predictions(inceptionv3_model, test_ds)\n",
    "- True and Predicted Classes:           true_classes,predicted_classes = true_pred_classes(inceptionv3_model, test_ds)\n",
    "- Accuracy:                             accuracy_score(true_classes,predicted_classes)\n",
    "- F1 Score:                             f1_score(true_classes, predicted_classes, average='weighted')\n",
    "- Recall:                               recall_score(true_classes, predicted_classes, average='weighted')\n",
    "- Precision:                            precision_score(true_classes, predicted_classes, average='weighted')\n",
    "- Confusion MAtrix (as Array):          conf_matrix = confusion_matrix(true_classes, predicted_classes)\n",
    "- Plot Confusion Matrix:                print_conf_matrix(true_classes, predicted_classes,class_names)\n",
    "- Upload a trained model to azure:      download_model_from_azure(\"model_name\")\n",
    "- Download a trained model from azure:  upload_model_to_azure(model, \"model_name\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "metadata": {},
   "outputs": [],
   "source": [
    "image_size=224\n",
    "channels=3\n",
    "autotune = tf.data.experimental.AUTOTUNE # Adapt preprocessing and prefetching dynamically\n",
    "\n",
    "def data_split(df):\n",
    "    \"\"\"Splits and returns the dataset into training, validation, and test\"\"\"\n",
    "    X_temp, X_test, y_temp, y_test = train_test_split(df['Image_Folder'], df['Label'], test_size=0.15, random_state=42)\n",
    "    X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.176, random_state=42)\n",
    "    #convert labels to array\n",
    "    y_train = np.array(y_train).tolist()\n",
    "    y_val = np.array(y_val).tolist()\n",
    "    y_test = np.array(y_test).tolist()\n",
    "    #print number of observations per datasets\n",
    "    print(\"Nr. Training:\",len(X_train),\"Nr. Validation:\",len(X_val),\"Nr. Test:\",len(X_test))\n",
    "    \n",
    "    return X_train, X_val, X_test, y_train, y_val, y_test\n",
    "\n",
    "\n",
    "def load_image(image_path):\n",
    "    \"\"\"Fetches image data from Azure Blob Storage.\"\"\"\n",
    "    try:\n",
    "        # Create a blob service client\n",
    "        blob_service_client = BlobServiceClient(account_url=\"https://<account_name>.blob.core.windows.net\", credential=\"<account_key>\")\n",
    "        blob_client = container_client.get_blob_client(image_path)\n",
    "\n",
    "        # Download the blob's contents as bytes\n",
    "        blob_data = blob_client.download_blob().readall()\n",
    "        \n",
    "        return blob_data\n",
    "    \n",
    "    except Exception as e:\n",
    "        print(f\"Error fetching image from Azure: {e}\")\n",
    "        # Return a default image or handle the error appropriately\n",
    "        return tf.zeros((image_size, image_size, channels), dtype=tf.uint8).numpy()\n",
    "\n",
    "def load_and_preprocess_image(path):\n",
    "    \"\"\"Loads an image, decodes it to grayscale, resizes, and normalizes it.\"\"\"\n",
    "    # Load image\n",
    "    image_file = load_image(path)\n",
    "    # Decode the image to grayscale\n",
    "    image_tensor = tf.io.decode_image(image_file, channels=channels)\n",
    "    # Resize the image\n",
    "    image_resized = tf.image.resize(image_tensor, [image_size, image_size])\n",
    "    # Normalize the image data\n",
    "    image_normalized = image_resized / 255.0\n",
    "    return image_normalized.numpy()\n",
    "\n",
    "def create_data_lists(filenames, labels):\n",
    "    \"\"\"Creates lists of images and labels.\"\"\"\n",
    "    X_train = []\n",
    "    y_train = []\n",
    "\n",
    "    for path, label in zip(filenames, labels):\n",
    "        image = load_and_preprocess_image(path)\n",
    "        X_train.append(image)\n",
    "        y_train.append(label)\n",
    "    \n",
    "    X_train = np.array(X_train)\n",
    "    y_train = np.array(y_train)\n",
    "    \n",
    "    # Convert labels to one-hot encoding\n",
    "    #y_train = tf.keras.utils.to_categorical(y_train, num_classes=7)\n",
    "    \n",
    "    return X_train, y_train\n",
    "\n",
    "\n",
    "def plot_history(model):\n",
    "    \"\"\"Plots the accuracy and loss of the inputted model.\"\"\"\n",
    "    # summarize history for accuracy\n",
    "    plt.plot(model.history['accuracy'])\n",
    "    plt.plot(model.history['val_accuracy'])\n",
    "    plt.title('model accuracy')\n",
    "    plt.ylabel('accuracy')\n",
    "    plt.xlabel('epoch')\n",
    "    plt.legend(['Train', 'Validation'], loc='upper left')\n",
    "    plt.show()\n",
    "    \n",
    "    # summarize history for loss\n",
    "    plt.plot(model.history['loss'])\n",
    "    plt.plot(model.history['val_loss'])\n",
    "    plt.title('model loss')\n",
    "    plt.ylabel('loss')\n",
    "    plt.xlabel('epoch')\n",
    "    plt.legend(['Train', 'Validation'], loc='upper left')\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "def print_predictions(labels, preds, predictions):\n",
    "    \"\"\"Predictions based on test dataset.\"\"\"\n",
    "    #predict\n",
    "    for label,pred, prediction in zip(labels, preds, predictions):\n",
    "        \n",
    "            print(\"Prediction:\", prediction,\"Pred. Class: \",pred, \"Actual Label:\", label)# Print the first prediction\n",
    "        \n",
    "    \n",
    "        \n",
    "def plot_model(model): \n",
    "    \"\"\"Plot model with predefined arguments.\"\"\"\n",
    "    plot_model(model, \n",
    "            to_file='vgg.png',\n",
    "            show_shapes=True,\n",
    "            show_dtype=True,\n",
    "            show_layer_names=True,\n",
    "            show_layer_activations=True,\n",
    "            show_trainable=False)\n",
    "    \n",
    "\n",
    "def evaluate_model(model, test_ds):\n",
    "    result = model.evaluate(test_ds)\n",
    "    # Assuming accuracy was the second metric (index 1), extract the accuracy.\n",
    "    test_accuracy = result[1] * 100  # Convert to percentage\n",
    "    print(f\"Test Accuracy: {test_accuracy:.2f}%\")\n",
    "    return test_accuracy\n",
    "\n",
    "\n",
    "def true_and_predicted_classes(predictions, labels):\n",
    "    predicted_classes = []\n",
    "    true_classes = []\n",
    "    for prediction in predictions:  \n",
    "        pred = np.argmax(prediction)\n",
    "        predicted_classes.append(pred)\n",
    "    for label in labels: \n",
    "        true = np.argmax(label)\n",
    "        true_classes.append(true)\n",
    "    return predicted_classes, true_classes\n",
    "\n",
    "\n",
    "def print_conf_matrix(true_classes, predicted_classes, class_names):\n",
    "    \"\"\"\n",
    "    Print confusion matrix.\n",
    "    \"\"\"\n",
    "    conf_matrix = confusion_matrix(true_classes, predicted_classes)\n",
    "    df_cm = pd.DataFrame(\n",
    "        conf_matrix, index=class_names, columns=class_names,\n",
    "    )\n",
    "    fig = plt.figure(figsize=(10,7))\n",
    "    heatmap = sns.heatmap(df_cm, annot=True, fmt=\"d\", cmap='Blues')\n",
    "\n",
    "    # Set aesthetics for better readability\n",
    "    heatmap.yaxis.set_ticklabels(heatmap.yaxis.get_ticklabels(), rotation=0, ha='right', fontsize=14)\n",
    "    heatmap.xaxis.set_ticklabels(heatmap.xaxis.get_ticklabels(), rotation=45, ha='right', fontsize=14)\n",
    "\n",
    "    plt.ylabel('True label')\n",
    "    plt.xlabel('Predicted label')\n",
    "    plt.title('Confusion Matrix')\n",
    "    plt.show()\n",
    "\n",
    "def plot_image(index, images, labels):\n",
    "    \"\"\"\n",
    "    Plots a single image with its predicted and actual labels.\n",
    "    \n",
    "    Parameters:\n",
    "    - image: The image data to plot.\n",
    "    - y_true: The true label of the image.\n",
    "    - y_pred: The predicted label of the image.\n",
    "    - class_names: List of class names for labels.\n",
    "    \"\"\"\n",
    "    # Get a single image from X_val\n",
    "    image = images[index]\n",
    "\n",
    "    # Get the true label for the image\n",
    "    y_true = np.argmax(labels[index])\n",
    "\n",
    "    # Predict the label using the model\n",
    "    y_pred = np.argmax(model.predict(np.expand_dims(image, axis=0)))\n",
    "\n",
    "    plt.figure(figsize=(3, 3))\n",
    "    plt.imshow(image, cmap='bone')\n",
    "    plt.xticks([])\n",
    "    plt.yticks([])\n",
    "    plt.xlabel(f\"True: {class_names[y_true]}\\nPred: {class_names[y_pred]}\",\n",
    "               color='black' if y_true == y_pred else 'red')\n",
    "    plt.title(\"Image with Predicted and Actual Labels\")\n",
    "    plt.show()\n",
    "\n",
    "def plot_wrong_pred_image(images, true_classes, predicted_classes):\n",
    "    \"\"\"\n",
    "    Plots a single image with its predicted and actual labels.\n",
    "    \n",
    "    Parameters:\n",
    "    - image: The image data to plot.\n",
    "    - y_true: The true label of the image.\n",
    "    - y_pred: The predicted label of the image.\n",
    "    - class_names: List of class names for labels.\n",
    "    \"\"\"\n",
    "    mismatch =  [i for i in range(len(true_classes)) if true_classes[i] != predicted_classes[i]]\n",
    "    random_nr = random.choice(mismatch)\n",
    "    # Get a single image from X_val\n",
    "    image = images[random_nr]\n",
    "\n",
    "    # Get the true label for the image\n",
    "    y_true = true_classes[random_nr]\n",
    "\n",
    "    # Predict the label using the model\n",
    "    y_pred = predicted_classes[random_nr]\n",
    "\n",
    "    plt.figure(figsize=(3, 3))\n",
    "    plt.imshow(image, cmap='bone')\n",
    "    plt.xticks([])\n",
    "    plt.yticks([])\n",
    "    plt.xlabel(f\"True: {class_names[y_true]}\\nPred: {class_names[y_pred]}\",\n",
    "               color='black' if y_true == y_pred else 'red')\n",
    "    plt.title(\"Wrong predicted image\")\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Setup"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Run the follwing cell to pip install the necerssary packages specified in the requirements.txt file."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: numpy in /home/ucloud/.local/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (1.26.4)\n",
      "Requirement already satisfied: azure-storage-blob in /home/ucloud/.local/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (12.20.0)\n",
      "Requirement already satisfied: pillow in /home/ucloud/.local/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (10.3.0)\n",
      "Requirement already satisfied: matplotlib in /home/ucloud/.local/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (3.8.4)\n",
      "Requirement already satisfied: pandas in /home/ucloud/.local/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (2.2.2)\n",
      "Requirement already satisfied: tensorflow in /home/ucloud/.local/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (2.16.1)\n",
      "Requirement already satisfied: tensorflow_hub in /home/ucloud/.local/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (0.16.1)\n",
      "Requirement already satisfied: scikit-learn in /home/ucloud/.local/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (1.4.2)\n",
      "Requirement already satisfied: seaborn in /home/ucloud/.local/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (0.13.2)\n",
      "Requirement already satisfied: azure-core>=1.28.0 in /home/ucloud/.local/lib/python3.12/site-packages (from azure-storage-blob->-r requirements.txt (line 2)) (1.30.1)\n",
      "Requirement already satisfied: cryptography>=2.1.4 in /usr/lib/python3/dist-packages (from azure-storage-blob->-r requirements.txt (line 2)) (41.0.7)\n",
      "Requirement already satisfied: typing-extensions>=4.6.0 in /home/ucloud/.local/lib/python3.12/site-packages (from azure-storage-blob->-r requirements.txt (line 2)) (4.11.0)\n",
      "Requirement already satisfied: isodate>=0.6.1 in /home/ucloud/.local/lib/python3.12/site-packages (from azure-storage-blob->-r requirements.txt (line 2)) (0.6.1)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /home/ucloud/.local/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (1.2.1)\n",
      "Requirement already satisfied: cycler>=0.10 in /home/ucloud/.local/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /home/ucloud/.local/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (4.51.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /home/ucloud/.local/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (1.4.5)\n",
      "Requirement already satisfied: packaging>=20.0 in /home/ucloud/.local/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (24.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib->-r requirements.txt (line 4)) (3.1.1)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /home/ucloud/.local/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/ucloud/.local/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 5)) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /home/ucloud/.local/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 5)) (2024.1)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (2.1.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (1.6.3)\n",
      "Requirement already satisfied: flatbuffers>=23.5.26 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (24.3.25)\n",
      "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (0.5.4)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (0.2.0)\n",
      "Requirement already satisfied: h5py>=3.10.0 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (3.11.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (18.1.1)\n",
      "Requirement already satisfied: ml-dtypes~=0.3.1 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (0.3.2)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (3.3.0)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (4.25.3)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (2.31.0)\n",
      "Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tensorflow->-r requirements.txt (line 6)) (68.1.2)\n",
      "Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow->-r requirements.txt (line 6)) (1.16.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (2.4.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (1.16.0)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (1.63.0)\n",
      "Requirement already satisfied: tensorboard<2.17,>=2.16 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (2.16.2)\n",
      "Requirement already satisfied: keras>=3.0.0 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 6)) (3.3.3)\n",
      "Requirement already satisfied: tf-keras>=2.14.1 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorflow_hub->-r requirements.txt (line 7)) (2.16.0)\n",
      "Requirement already satisfied: scipy>=1.6.0 in /home/ucloud/.local/lib/python3.12/site-packages (from scikit-learn->-r requirements.txt (line 8)) (1.13.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in /home/ucloud/.local/lib/python3.12/site-packages (from scikit-learn->-r requirements.txt (line 8)) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ucloud/.local/lib/python3.12/site-packages (from scikit-learn->-r requirements.txt (line 8)) (3.5.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->tensorflow->-r requirements.txt (line 6)) (0.42.0)\n",
      "Requirement already satisfied: rich in /home/ucloud/.local/lib/python3.12/site-packages (from keras>=3.0.0->tensorflow->-r requirements.txt (line 6)) (13.7.1)\n",
      "Requirement already satisfied: namex in /home/ucloud/.local/lib/python3.12/site-packages (from keras>=3.0.0->tensorflow->-r requirements.txt (line 6)) (0.0.8)\n",
      "Requirement already satisfied: optree in /home/ucloud/.local/lib/python3.12/site-packages (from keras>=3.0.0->tensorflow->-r requirements.txt (line 6)) (0.11.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/ucloud/.local/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow->-r requirements.txt (line 6)) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/ucloud/.local/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow->-r requirements.txt (line 6)) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ucloud/.local/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow->-r requirements.txt (line 6)) (2.2.1)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/ucloud/.local/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow->-r requirements.txt (line 6)) (2024.2.2)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorboard<2.17,>=2.16->tensorflow->-r requirements.txt (line 6)) (3.6)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorboard<2.17,>=2.16->tensorflow->-r requirements.txt (line 6)) (0.7.2)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /home/ucloud/.local/lib/python3.12/site-packages (from tensorboard<2.17,>=2.16->tensorflow->-r requirements.txt (line 6)) (3.0.3)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /home/ucloud/.local/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow->-r requirements.txt (line 6)) (2.1.5)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /home/ucloud/.local/lib/python3.12/site-packages (from rich->keras>=3.0.0->tensorflow->-r requirements.txt (line 6)) (3.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ucloud/.local/lib/python3.12/site-packages (from rich->keras>=3.0.0->tensorflow->-r requirements.txt (line 6)) (2.18.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /home/ucloud/.local/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow->-r requirements.txt (line 6)) (0.1.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install -r requirements.txt"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "to push/pull form ucloud enter following code in terminal\n",
    "-  git config --global user.name \"FIRST_NAME LAST_NAME\"\n",
    "-  git config --global user.email \"MY_NAME@example.com\"\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Importing the necessary packages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-05-15 11:56:22.117338: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.\n",
      "2024-05-15 11:56:22.121301: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.\n",
      "2024-05-15 11:56:22.170140: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-05-15 11:56:23.109896: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import io\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "from azure.storage.blob import BlobServiceClient, ContainerClient\n",
    "from azure.core.exceptions import ResourceNotFoundError\n",
    "from PIL import Image\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import ast\n",
    "import time\n",
    "from keras.models import load_model\n",
    "import tempfile\n",
    "\n",
    "import pandas as pd\n",
    "from tensorflow.keras import layers, models\n",
    "import tensorflow_hub as hub\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "from sklearn.model_selection import train_test_split\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping\n",
    "from keras.applications.inception_v3 import InceptionV3\n",
    "from keras.applications.vgg16 import VGG16\n",
    "from keras.applications.vgg16 import preprocess_input\n",
    "from tensorflow.keras.applications import MobileNetV2\n",
    "from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Dense, Flatten, Dropout, GlobalAveragePooling2D\n",
    "from tensorflow.keras.models import Model, Sequential\n",
    "from keras.utils import plot_model\n",
    "from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix\n",
    "from keras.callbacks import Callback, ReduceLROnPlateau, EarlyStopping, ModelCheckpoint"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Connect to Azure"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "#set up storage\n",
    "connection_string = \"DefaultEndpointsProtocol=https;AccountName=mlfinalexam5505462853;AccountKey=0c40lghglG5/GlNK9yujDQAgo38GKoS2I3DeC/g22hwAEIFANKpmC/TqOpRk4RCT1DbfNiHBFt72+AStB+PfUA==;EndpointSuffix=core.windows.net\"\n",
    "container_name = \"meterml\"\n",
    "\n",
    "#create client\n",
    "blob_service_client = BlobServiceClient.from_connection_string(connection_string)\n",
    "container_client = blob_service_client.get_container_client(container_name)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Load Image Paths and Labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import ast\n",
    "import numpy as np\n",
    "#get filepaths\n",
    "df_train= pd.read_csv(\"FINAL_METER_ML_train_2000.csv\")\n",
    "df_val = pd.read_csv(\"FINAL_METER_ML_val.csv\")\n",
    "df_test = pd.read_csv(\"FINAL_METER_ML_test.csv\")\n",
    "\n",
    "# convert each string in the DataFrame to a list\n",
    "df_train['Label'] = df_train['Label'].apply(ast.literal_eval).apply(np.array)\n",
    "df_val['Label'] = df_val['Label'].apply(ast.literal_eval).apply(np.array)\n",
    "df_test['Label'] = df_test['Label'].apply(ast.literal_eval).apply(np.array)\n",
    "\n",
    "\n",
    "# convert each list in the DataFrame to a numpy array\n",
    "df['Label'] = df['Label'].apply(np.array)\n",
    "\n",
    "class_names=[\"CAFOs\",\"Landfills\",\"Mines\",\"Negative\",\"ProcessingPlants\",\"RefineriesAndTerminals\",\"WWTreatment\"]\n",
    "\n",
    "X_train = df_train['Image_Folder']\n",
    "X_val = df_val['Image_Folder']\n",
    "X_test = df_test['Image_Folder']\n",
    "\n",
    "\n",
    "y_train = np.array(df_train['Label']).tolist()\n",
    "y_val = np.array(df_val['Label']).tolist()\n",
    "y_test = np.array(df_test['Label']).tolist()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train, y_train = create_data_lists(X_train, y_train)\n",
    "X_val, y_val = create_data_lists(X_val, y_val)\n",
    "X_test, y_test = create_data_lists(X_test, y_test)\n",
    "\n",
    "# Save the array to a file\n",
    "np.save('x_train.npy', X_train)\n",
    "np.save('x_test.npy', X_test)\n",
    "np.save('x_val.npy', X_val)\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Models"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## ResNet50: \n",
    "- https://datagen.tech/guides/computer-vision/resnet-50/\n",
    "- https://medium.com/@bravinwasike18/building-a-deep-learning-model-with-keras-and-resnet-50-9dd6f4eb3351\n",
    "- https://medium.com/@ozgunhaznedar/image-classification-on-satellite-images-with-deep-learning-baa9813dde4e\n",
    "- https://wandb.ai/mostafaibrahim17/ml-articles/reports/The-Basics-of-ResNet50---Vmlldzo2NDkwNDE2#step-4:-building-resnet-50-model"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Transfer Learning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224\n'y' sizes: 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[40], line 36\u001b[0m\n\u001b[1;32m     33\u001b[0m t0 \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()\n\u001b[1;32m     35\u001b[0m \u001b[38;5;66;03m# Train model \u001b[39;00m\n\u001b[0;32m---> 36\u001b[0m history \u001b[38;5;241m=\u001b[39m \u001b[43mresnet_model\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_val\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     37\u001b[0m \u001b[43m                        \u001b[49m\u001b[43my_val\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     38\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mval_ds\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     39\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mepochs\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mtrain_epochs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     40\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbatch_size\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     41\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43m[\u001b[49m\u001b[43mReduceLROnPlateau\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpatience\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mEarlyStopping\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpatience\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     42\u001b[0m t1 \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()\n\u001b[1;32m     44\u001b[0m \u001b[38;5;66;03m#print time in seconds\u001b[39;00m\n",
      "File \u001b[0;32m~/.local/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py:122\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    119\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m    121\u001b[0m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m--> 122\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    124\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/.local/lib/python3.12/site-packages/keras/src/trainers/data_adapters/data_adapter_utils.py:114\u001b[0m, in \u001b[0;36mcheck_data_cardinality\u001b[0;34m(data)\u001b[0m\n\u001b[1;32m    110\u001b[0m     sizes \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m, \u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mjoin(\n\u001b[1;32m    111\u001b[0m         \u001b[38;5;28mstr\u001b[39m(i\u001b[38;5;241m.\u001b[39mshape[\u001b[38;5;241m0\u001b[39m]) \u001b[38;5;28;01mfor\u001b[39;00m i \u001b[38;5;129;01min\u001b[39;00m tree\u001b[38;5;241m.\u001b[39mflatten(single_data)\n\u001b[1;32m    112\u001b[0m     )\n\u001b[1;32m    113\u001b[0m     msg \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mlabel\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m sizes: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00msizes\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m--> 114\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(msg)\n",
      "\u001b[0;31mValueError\u001b[0m: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224\n'y' sizes: 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7\n"
     ]
    }
   ],
   "source": [
    "#set variables\n",
    "train_epochs = 30\n",
    "tune_epochs = 10\n",
    "total_epochs = train_epochs + tune_epochs\n",
    "batch_size = 128\n",
    "\n",
    "# import resnet model for transfer learning\n",
    "rn50_base = tf.keras.applications.ResNet50(\n",
    "    include_top = False,\n",
    "    weights = \"imagenet\",\n",
    "    input_shape=(224,224,3)\n",
    "    )\n",
    "\n",
    "# Freeze layers pf basemodel, so the pre-trained weights are fixed\n",
    "for each_layer in rn50_base.layers:\n",
    "        each_layer.trainable=False\n",
    "\n",
    "# create sequential model\n",
    "resnet_model = Sequential()\n",
    "\n",
    "# Add output layers for finetuning\n",
    "resnet_model.add(rn50_base)\n",
    "resnet_model.add(Flatten()) #use flatten instead of GlobalAveragePooling2D as it may yield better results when enough data\n",
    "resnet_model.add(Dense(512, activation='relu'))\n",
    "resnet_model.add(Dense(7, activation='softmax'))\n",
    "\n",
    "# Compile model\n",
    "resnet_model.compile(optimizer= tf.keras.optimizers.Adam(),\n",
    "                    loss= tf.keras.losses.CategoricalCrossentropy(), \n",
    "                    metrics = ['accuracy'])\n",
    "\n",
    "#initializt time\n",
    "t0 = time.time()\n",
    "\n",
    "# Train model \n",
    "history = resnet_model.fit(X_train,\n",
    "                        y_train,\n",
    "                        validation_data = (X_val,y_val)), \n",
    "                        epochs = train_epochs, \n",
    "                        batch_size=batch_size, \n",
    "                        callbacks = [ReduceLROnPlateau(patience=5), EarlyStopping(patience=5)])\n",
    "t1 = time.time()\n",
    "\n",
    "#print time in seconds\n",
    "print(\"Training time in seconds:\", t1-t0)\n",
    "\n",
    "#save model\n",
    "resnet_model.save(\"resnet_model.keras\")\n",
    "\n",
    "# Plot model information\n",
    "plot_history(history)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Fine Tuning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 input_layer_3 - False\n",
      "1 conv1_pad - False\n",
      "2 conv1_conv - False\n",
      "3 conv1_bn - False\n",
      "4 conv1_relu - False\n",
      "5 pool1_pad - False\n",
      "6 pool1_pool - False\n",
      "7 conv2_block1_1_conv - False\n",
      "8 conv2_block1_1_bn - False\n",
      "9 conv2_block1_1_relu - False\n",
      "10 conv2_block1_2_conv - False\n",
      "11 conv2_block1_2_bn - False\n",
      "12 conv2_block1_2_relu - False\n",
      "13 conv2_block1_0_conv - False\n",
      "14 conv2_block1_3_conv - False\n",
      "15 conv2_block1_0_bn - False\n",
      "16 conv2_block1_3_bn - False\n",
      "17 conv2_block1_add - False\n",
      "18 conv2_block1_out - False\n",
      "19 conv2_block2_1_conv - False\n",
      "20 conv2_block2_1_bn - False\n",
      "21 conv2_block2_1_relu - False\n",
      "22 conv2_block2_2_conv - False\n",
      "23 conv2_block2_2_bn - False\n",
      "24 conv2_block2_2_relu - False\n",
      "25 conv2_block2_3_conv - False\n",
      "26 conv2_block2_3_bn - False\n",
      "27 conv2_block2_add - False\n",
      "28 conv2_block2_out - False\n",
      "29 conv2_block3_1_conv - False\n",
      "30 conv2_block3_1_bn - False\n",
      "31 conv2_block3_1_relu - False\n",
      "32 conv2_block3_2_conv - False\n",
      "33 conv2_block3_2_bn - False\n",
      "34 conv2_block3_2_relu - False\n",
      "35 conv2_block3_3_conv - False\n",
      "36 conv2_block3_3_bn - False\n",
      "37 conv2_block3_add - False\n",
      "38 conv2_block3_out - False\n",
      "39 conv3_block1_1_conv - False\n",
      "40 conv3_block1_1_bn - False\n",
      "41 conv3_block1_1_relu - False\n",
      "42 conv3_block1_2_conv - False\n",
      "43 conv3_block1_2_bn - False\n",
      "44 conv3_block1_2_relu - False\n",
      "45 conv3_block1_0_conv - False\n",
      "46 conv3_block1_3_conv - False\n",
      "47 conv3_block1_0_bn - False\n",
      "48 conv3_block1_3_bn - False\n",
      "49 conv3_block1_add - False\n",
      "50 conv3_block1_out - False\n",
      "51 conv3_block2_1_conv - False\n",
      "52 conv3_block2_1_bn - False\n",
      "53 conv3_block2_1_relu - False\n",
      "54 conv3_block2_2_conv - False\n",
      "55 conv3_block2_2_bn - False\n",
      "56 conv3_block2_2_relu - False\n",
      "57 conv3_block2_3_conv - False\n",
      "58 conv3_block2_3_bn - False\n",
      "59 conv3_block2_add - False\n",
      "60 conv3_block2_out - False\n",
      "61 conv3_block3_1_conv - False\n",
      "62 conv3_block3_1_bn - False\n",
      "63 conv3_block3_1_relu - False\n",
      "64 conv3_block3_2_conv - False\n",
      "65 conv3_block3_2_bn - False\n",
      "66 conv3_block3_2_relu - False\n",
      "67 conv3_block3_3_conv - False\n",
      "68 conv3_block3_3_bn - False\n",
      "69 conv3_block3_add - False\n",
      "70 conv3_block3_out - False\n",
      "71 conv3_block4_1_conv - False\n",
      "72 conv3_block4_1_bn - False\n",
      "73 conv3_block4_1_relu - False\n",
      "74 conv3_block4_2_conv - False\n",
      "75 conv3_block4_2_bn - False\n",
      "76 conv3_block4_2_relu - False\n",
      "77 conv3_block4_3_conv - False\n",
      "78 conv3_block4_3_bn - False\n",
      "79 conv3_block4_add - False\n",
      "80 conv3_block4_out - False\n",
      "81 conv4_block1_1_conv - False\n",
      "82 conv4_block1_1_bn - False\n",
      "83 conv4_block1_1_relu - False\n",
      "84 conv4_block1_2_conv - False\n",
      "85 conv4_block1_2_bn - False\n",
      "86 conv4_block1_2_relu - False\n",
      "87 conv4_block1_0_conv - False\n",
      "88 conv4_block1_3_conv - False\n",
      "89 conv4_block1_0_bn - False\n",
      "90 conv4_block1_3_bn - False\n",
      "91 conv4_block1_add - False\n",
      "92 conv4_block1_out - False\n",
      "93 conv4_block2_1_conv - False\n",
      "94 conv4_block2_1_bn - False\n",
      "95 conv4_block2_1_relu - False\n",
      "96 conv4_block2_2_conv - False\n",
      "97 conv4_block2_2_bn - False\n",
      "98 conv4_block2_2_relu - False\n",
      "99 conv4_block2_3_conv - False\n",
      "100 conv4_block2_3_bn - False\n",
      "101 conv4_block2_add - False\n",
      "102 conv4_block2_out - False\n",
      "103 conv4_block3_1_conv - False\n",
      "104 conv4_block3_1_bn - False\n",
      "105 conv4_block3_1_relu - False\n",
      "106 conv4_block3_2_conv - False\n",
      "107 conv4_block3_2_bn - False\n",
      "108 conv4_block3_2_relu - False\n",
      "109 conv4_block3_3_conv - False\n",
      "110 conv4_block3_3_bn - False\n",
      "111 conv4_block3_add - False\n",
      "112 conv4_block3_out - False\n",
      "113 conv4_block4_1_conv - False\n",
      "114 conv4_block4_1_bn - False\n",
      "115 conv4_block4_1_relu - False\n",
      "116 conv4_block4_2_conv - False\n",
      "117 conv4_block4_2_bn - False\n",
      "118 conv4_block4_2_relu - False\n",
      "119 conv4_block4_3_conv - False\n",
      "120 conv4_block4_3_bn - False\n",
      "121 conv4_block4_add - False\n",
      "122 conv4_block4_out - False\n",
      "123 conv4_block5_1_conv - False\n",
      "124 conv4_block5_1_bn - False\n",
      "125 conv4_block5_1_relu - False\n",
      "126 conv4_block5_2_conv - False\n",
      "127 conv4_block5_2_bn - False\n",
      "128 conv4_block5_2_relu - False\n",
      "129 conv4_block5_3_conv - False\n",
      "130 conv4_block5_3_bn - False\n",
      "131 conv4_block5_add - False\n",
      "132 conv4_block5_out - False\n",
      "133 conv4_block6_1_conv - False\n",
      "134 conv4_block6_1_bn - False\n",
      "135 conv4_block6_1_relu - False\n",
      "136 conv4_block6_2_conv - False\n",
      "137 conv4_block6_2_bn - False\n",
      "138 conv4_block6_2_relu - False\n",
      "139 conv4_block6_3_conv - False\n",
      "140 conv4_block6_3_bn - False\n",
      "141 conv4_block6_add - False\n",
      "142 conv4_block6_out - False\n",
      "143 conv5_block1_1_conv - True\n",
      "144 conv5_block1_1_bn - True\n",
      "145 conv5_block1_1_relu - True\n",
      "146 conv5_block1_2_conv - True\n",
      "147 conv5_block1_2_bn - True\n",
      "148 conv5_block1_2_relu - True\n",
      "149 conv5_block1_0_conv - True\n",
      "150 conv5_block1_3_conv - True\n",
      "151 conv5_block1_0_bn - True\n",
      "152 conv5_block1_3_bn - True\n",
      "153 conv5_block1_add - True\n",
      "154 conv5_block1_out - True\n",
      "155 conv5_block2_1_conv - True\n",
      "156 conv5_block2_1_bn - True\n",
      "157 conv5_block2_1_relu - True\n",
      "158 conv5_block2_2_conv - True\n",
      "159 conv5_block2_2_bn - True\n",
      "160 conv5_block2_2_relu - True\n",
      "161 conv5_block2_3_conv - True\n",
      "162 conv5_block2_3_bn - True\n",
      "163 conv5_block2_add - True\n",
      "164 conv5_block2_out - True\n",
      "165 conv5_block3_1_conv - True\n",
      "166 conv5_block3_1_bn - True\n",
      "167 conv5_block3_1_relu - True\n",
      "168 conv5_block3_2_conv - True\n",
      "169 conv5_block3_2_bn - True\n",
      "170 conv5_block3_2_relu - True\n",
      "171 conv5_block3_3_conv - True\n",
      "172 conv5_block3_3_bn - True\n",
      "173 conv5_block3_add - True\n",
      "174 conv5_block3_out - True\n"
     ]
    }
   ],
   "source": [
    "#unfreeze last convolution layer for fine tuning\n",
    "for each_layer in rn50_base.layers:\n",
    "        each_layer.trainable=False\n",
    "for layer in [l for l in rn50_base.layers if 'conv5' in l.name]:\n",
    "   layer.trainable = True\n",
    "   \n",
    "for i, layer in enumerate(rn50_base.layers):\n",
    "    print(i, layer.name, \"-\", layer.trainable)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/40\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-05-15 06:33:12.617525: W tensorflow/core/kernels/data/cache_dataset_ops.cc:858] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 4s/step - accuracy: 0.6880 - loss: 1.7288"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-05-15 06:43:01.728517: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:0e4d209e-201e-0046-3b82-a67091000000\n",
      "Time:2024-05-15T04:43:01.7181094Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:0e4d209e-201e-0046-3b82-a67091000000\n",
      "Time:2024-05-15T04:43:01.7181094Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:0e4d209e-201e-0046-3b82-a67091000000\n",
      "Time:2024-05-15T04:43:01.7181094Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:0e4d209e-201e-0046-3b82-a67091000000\n",
      "Time:2024-05-15T04:43:01.7181094Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.762306: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:0e4d20b8-201e-0046-5382-a67091000000\n",
      "Time:2024-05-15T04:43:01.7509637Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:0e4d20b8-201e-0046-5382-a67091000000\n",
      "Time:2024-05-15T04:43:01.7509637Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:0e4d20b8-201e-0046-5382-a67091000000\n",
      "Time:2024-05-15T04:43:01.7509637Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:0e4d20b8-201e-0046-5382-a67091000000\n",
      "Time:2024-05-15T04:43:01.7509637Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.789942: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:05bbb314-901e-0031-6c82-a6a505000000\n",
      "Time:2024-05-15T04:43:01.7676398Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:05bbb314-901e-0031-6c82-a6a505000000\n",
      "Time:2024-05-15T04:43:01.7676398Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:05bbb314-901e-0031-6c82-a6a505000000\n",
      "Time:2024-05-15T04:43:01.7676398Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:05bbb314-901e-0031-6c82-a6a505000000\n",
      "Time:2024-05-15T04:43:01.7676398Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.791530: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:ea6ed3da-301e-0075-4882-a62f3a000000\n",
      "Time:2024-05-15T04:43:01.7762631Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ea6ed3da-301e-0075-4882-a62f3a000000\n",
      "Time:2024-05-15T04:43:01.7762631Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:ea6ed3da-301e-0075-4882-a62f3a000000\n",
      "Time:2024-05-15T04:43:01.7762631Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ea6ed3da-301e-0075-4882-a62f3a000000\n",
      "Time:2024-05-15T04:43:01.7762631Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.793199: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:5ed04893-501e-0073-2e82-a61c85000000\n",
      "Time:2024-05-15T04:43:01.7731685Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:5ed04893-501e-0073-2e82-a61c85000000\n",
      "Time:2024-05-15T04:43:01.7731685Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:5ed04893-501e-0073-2e82-a61c85000000\n",
      "Time:2024-05-15T04:43:01.7731685Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:5ed04893-501e-0073-2e82-a61c85000000\n",
      "Time:2024-05-15T04:43:01.7731685Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.796518: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:728e05fc-201e-008d-3982-a673c4000000\n",
      "Time:2024-05-15T04:43:01.7697595Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:728e05fc-201e-008d-3982-a673c4000000\n",
      "Time:2024-05-15T04:43:01.7697595Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:728e05fc-201e-008d-3982-a673c4000000\n",
      "Time:2024-05-15T04:43:01.7697595Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:728e05fc-201e-008d-3982-a673c4000000\n",
      "Time:2024-05-15T04:43:01.7697595Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.797680: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:812f412f-401e-00a4-6882-a64db0000000\n",
      "Time:2024-05-15T04:43:01.7891173Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:812f412f-401e-00a4-6882-a64db0000000\n",
      "Time:2024-05-15T04:43:01.7891173Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:812f412f-401e-00a4-6882-a64db0000000\n",
      "Time:2024-05-15T04:43:01.7891173Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:812f412f-401e-00a4-6882-a64db0000000\n",
      "Time:2024-05-15T04:43:01.7891173Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.799917: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:8cf845a8-d01e-0020-1182-a63fb1000000\n",
      "Time:2024-05-15T04:43:01.7706296Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:8cf845a8-d01e-0020-1182-a63fb1000000\n",
      "Time:2024-05-15T04:43:01.7706296Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:8cf845a8-d01e-0020-1182-a63fb1000000\n",
      "Time:2024-05-15T04:43:01.7706296Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:8cf845a8-d01e-0020-1182-a63fb1000000\n",
      "Time:2024-05-15T04:43:01.7706296Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.801642: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:1a892947-201e-009d-2082-a6b6ac000000\n",
      "Time:2024-05-15T04:43:01.7709953Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:1a892947-201e-009d-2082-a6b6ac000000\n",
      "Time:2024-05-15T04:43:01.7709953Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:1a892947-201e-009d-2082-a6b6ac000000\n",
      "Time:2024-05-15T04:43:01.7709953Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:1a892947-201e-009d-2082-a6b6ac000000\n",
      "Time:2024-05-15T04:43:01.7709953Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.846385: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:a68494f0-401e-0050-4f82-a68646000000\n",
      "Time:2024-05-15T04:43:01.8350190Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:a68494f0-401e-0050-4f82-a68646000000\n",
      "Time:2024-05-15T04:43:01.8350190Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:a68494f0-401e-0050-4f82-a68646000000\n",
      "Time:2024-05-15T04:43:01.8350190Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:a68494f0-401e-0050-4f82-a68646000000\n",
      "Time:2024-05-15T04:43:01.8350190Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.854626: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:43d8b5e4-801e-0012-1682-a63fc6000000\n",
      "Time:2024-05-15T04:43:01.8447964Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:43d8b5e4-801e-0012-1682-a63fc6000000\n",
      "Time:2024-05-15T04:43:01.8447964Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:43d8b5e4-801e-0012-1682-a63fc6000000\n",
      "Time:2024-05-15T04:43:01.8447964Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:43d8b5e4-801e-0012-1682-a63fc6000000\n",
      "Time:2024-05-15T04:43:01.8447964Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.862780: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:b755a478-b01e-008f-6d82-a6cd7c000000\n",
      "Time:2024-05-15T04:43:01.8479414Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b755a478-b01e-008f-6d82-a6cd7c000000\n",
      "Time:2024-05-15T04:43:01.8479414Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:b755a478-b01e-008f-6d82-a6cd7c000000\n",
      "Time:2024-05-15T04:43:01.8479414Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b755a478-b01e-008f-6d82-a6cd7c000000\n",
      "Time:2024-05-15T04:43:01.8479414Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.874234: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:5a3748b7-401e-0022-2d82-a68109000000\n",
      "Time:2024-05-15T04:43:01.8457800Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:5a3748b7-401e-0022-2d82-a68109000000\n",
      "Time:2024-05-15T04:43:01.8457800Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:5a3748b7-401e-0022-2d82-a68109000000\n",
      "Time:2024-05-15T04:43:01.8457800Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:5a3748b7-401e-0022-2d82-a68109000000\n",
      "Time:2024-05-15T04:43:01.8457800Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.894196: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:334ff8c7-c01e-0013-4582-a6601a000000\n",
      "Time:2024-05-15T04:43:01.8538162Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:334ff8c7-c01e-0013-4582-a6601a000000\n",
      "Time:2024-05-15T04:43:01.8538162Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:334ff8c7-c01e-0013-4582-a6601a000000\n",
      "Time:2024-05-15T04:43:01.8538162Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:334ff8c7-c01e-0013-4582-a6601a000000\n",
      "Time:2024-05-15T04:43:01.8538162Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.895870: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:a79e97a5-001e-006e-2b82-a61139000000\n",
      "Time:2024-05-15T04:43:01.8680821Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:a79e97a5-001e-006e-2b82-a61139000000\n",
      "Time:2024-05-15T04:43:01.8680821Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:a79e97a5-001e-006e-2b82-a61139000000\n",
      "Time:2024-05-15T04:43:01.8680821Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:a79e97a5-001e-006e-2b82-a61139000000\n",
      "Time:2024-05-15T04:43:01.8680821Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.897041: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:a8f53dc8-001e-0033-3082-a61bbd000000\n",
      "Time:2024-05-15T04:43:01.8601922Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:a8f53dc8-001e-0033-3082-a61bbd000000\n",
      "Time:2024-05-15T04:43:01.8601922Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:a8f53dc8-001e-0033-3082-a61bbd000000\n",
      "Time:2024-05-15T04:43:01.8601922Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:a8f53dc8-001e-0033-3082-a61bbd000000\n",
      "Time:2024-05-15T04:43:01.8601922Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.898807: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:77317296-f01e-009e-0182-a657c8000000\n",
      "Time:2024-05-15T04:43:01.8576255Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:77317296-f01e-009e-0182-a657c8000000\n",
      "Time:2024-05-15T04:43:01.8576255Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:77317296-f01e-009e-0182-a657c8000000\n",
      "Time:2024-05-15T04:43:01.8576255Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:77317296-f01e-009e-0182-a657c8000000\n",
      "Time:2024-05-15T04:43:01.8576255Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 06:43:01.899285: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:ea6ed3da-301e-0075-4882-a62f3a000000\n",
      "Time:2024-05-15T04:43:01.7762631Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ea6ed3da-301e-0075-4882-a62f3a000000\n",
      "Time:2024-05-15T04:43:01.7762631Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:ea6ed3da-301e-0075-4882-a62f3a000000\n",
      "Time:2024-05-15T04:43:01.7762631Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ea6ed3da-301e-0075-4882-a62f3a000000\n",
      "Time:2024-05-15T04:43:01.7762631Z</Message></Error>\n",
      "\n",
      "\n",
      "\t [[{{node EagerPyFunc}}]]\n",
      "\t [[IteratorGetNext]]\n"
     ]
    },
    {
     "ename": "UnknownError",
     "evalue": "Graph execution error:\n\nDetected at node EagerPyFunc defined at (most recent call last):\n<stack traces unavailable>\nHttpResponseError: The specified account is disabled.\nRequestId:ea6ed3da-301e-0075-4882-a62f3a000000\nTime:2024-05-15T04:43:01.7762631Z\nErrorCode:AccountIsDisabled\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\nRequestId:ea6ed3da-301e-0075-4882-a62f3a000000\nTime:2024-05-15T04:43:01.7762631Z</Message></Error>\nTraceback (most recent call last):\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n    return func(device, token, args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n    outputs = self._call(device, args)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n    ret = self._func(*args)\n          ^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n    image_file = load_image(path.numpy().decode('utf-8'))\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n    return StorageStreamDownloader(**options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n    self._response = self._initial_request()\n                     ^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n    process_storage_error(error)\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"<string>\", line 1, in <module>\n\nazure.core.exceptions.HttpResponseError: The specified account is disabled.\nRequestId:ea6ed3da-301e-0075-4882-a62f3a000000\nTime:2024-05-15T04:43:01.7762631Z\nErrorCode:AccountIsDisabled\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\nRequestId:ea6ed3da-301e-0075-4882-a62f3a000000\nTime:2024-05-15T04:43:01.7762631Z</Message></Error>\n\n\n\t [[{{node EagerPyFunc}}]]\n\t [[IteratorGetNext]] [Op:__inference_one_step_on_iterator_609517]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnknownError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[27], line 10\u001b[0m\n\u001b[1;32m      7\u001b[0m t0 \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()\n\u001b[1;32m      9\u001b[0m \u001b[38;5;66;03m# Train model \u001b[39;00m\n\u001b[0;32m---> 10\u001b[0m history \u001b[38;5;241m=\u001b[39m \u001b[43mresnet_model\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrain_ds\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     11\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mval_ds\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     12\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtotal_epochs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     13\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbatch_size\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     14\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43m[\u001b[49m\u001b[43mReduceLROnPlateau\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpatience\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mEarlyStopping\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpatience\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     15\u001b[0m t1 \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()\n\u001b[1;32m     16\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTraining time in seconds:\u001b[39m\u001b[38;5;124m\"\u001b[39m, t1\u001b[38;5;241m-\u001b[39mt0)\n",
      "File \u001b[0;32m~/.local/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py:122\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    119\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m    121\u001b[0m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m--> 122\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    124\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/.local/lib/python3.12/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mUnknownError\u001b[0m: Graph execution error:\n\nDetected at node EagerPyFunc defined at (most recent call last):\n<stack traces unavailable>\nHttpResponseError: The specified account is disabled.\nRequestId:ea6ed3da-301e-0075-4882-a62f3a000000\nTime:2024-05-15T04:43:01.7762631Z\nErrorCode:AccountIsDisabled\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\nRequestId:ea6ed3da-301e-0075-4882-a62f3a000000\nTime:2024-05-15T04:43:01.7762631Z</Message></Error>\nTraceback (most recent call last):\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n    return func(device, token, args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n    outputs = self._call(device, args)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n    ret = self._func(*args)\n          ^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/tmp/ipykernel_5528/2941140567.py\", line 30, in load_and_preprocess_image\n    image_file = load_image(path.numpy().decode('utf-8'))\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/tmp/ipykernel_5528/2941140567.py\", line 22, in load_image\n    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n    return StorageStreamDownloader(**options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n    self._response = self._initial_request()\n                     ^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n    process_storage_error(error)\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"<string>\", line 1, in <module>\n\nazure.core.exceptions.HttpResponseError: The specified account is disabled.\nRequestId:ea6ed3da-301e-0075-4882-a62f3a000000\nTime:2024-05-15T04:43:01.7762631Z\nErrorCode:AccountIsDisabled\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\nRequestId:ea6ed3da-301e-0075-4882-a62f3a000000\nTime:2024-05-15T04:43:01.7762631Z</Message></Error>\n\n\n\t [[{{node EagerPyFunc}}]]\n\t [[IteratorGetNext]] [Op:__inference_one_step_on_iterator_609517]"
     ]
    }
   ],
   "source": [
    "#compile the model with smaller learning rate\n",
    "resnet_model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate = 0.0001),\n",
    "                    loss = tf.keras.losses.CategoricalCrossentropy(), \n",
    "                    metrics=['accuracy'])\n",
    "\n",
    "#initialize timing\n",
    "t0 = time.time()\n",
    "\n",
    "# Train model \n",
    "history = resnet_model.fit(X_train,\n",
    "                        y_train\n",
    "                        validation_data = (X_val,y_val)), \n",
    "                        epochs=total_epochs, \n",
    "                        batch_size=batch_size, \n",
    "                        callbacks = [ReduceLROnPlateau(patience=5), EarlyStopping(patience=5)])\n",
    "t1 = time.time()\n",
    "print(\"Training time in seconds:\", t1-t0)\n",
    "\n",
    "#save trained model\n",
    "resnet_model.save(\"resnet_model_tf.keras\")\n",
    "\n",
    "# Plot training plots\n",
    "plot_history(history)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
