{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Setup"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Run the follwing cell to pip install the necerssary packages specified in the requirements.txt file."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "#pip install -r requirements.txt"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# to push/pull form ucloud enter following code in terminal\n",
    "git config --global user.name \"FIRST_NAME LAST_NAME\"\n",
    "git config --global user.email \"MY_NAME@example.com\"\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Importing the necessary packages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import io\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "from azure.storage.blob import BlobServiceClient, ContainerClient\n",
    "from azure.core.exceptions import ResourceNotFoundError\n",
    "from PIL import Image\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import ast\n",
    "import time\n",
    "from keras.models import load_model\n",
    "import tempfile\n",
    "\n",
    "import pandas as pd\n",
    "from tensorflow.keras import layers, models\n",
    "import tensorflow_hub as hub\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "from sklearn.model_selection import train_test_split\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping\n",
    "from keras.applications.inception_v3 import InceptionV3\n",
    "from keras.applications.vgg16 import VGG16\n",
    "from keras.applications.vgg16 import preprocess_input\n",
    "from tensorflow.keras.applications import MobileNetV2\n",
    "from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Dense, Flatten, Dropout, GlobalAveragePooling2D\n",
    "from tensorflow.keras.models import Model, Sequential\n",
    "from keras.utils import plot_model\n",
    "from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix\n",
    "from keras.callbacks import Callback, ReduceLROnPlateau, EarlyStopping, ModelCheckpoint"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Helper Functions \n",
    "\n",
    "- Training Accuracy and Loss Graphs: plot_history(history)\n",
    "- Predictions: print_predictions(inceptionv3_model, test_ds)\n",
    "- True and Predicted Classes: true_classes,predicted_classes = true_pred_classes(inceptionv3_model, test_ds)\n",
    "- Accuracy: accuracy_score(true_classes,predicted_classes)\n",
    "- F1 Score: f1_score(true_classes, predicted_classes, average='weighted')\n",
    "- Recall: recall = recall_score(true_classes, predicted_classes, average='weighted')\n",
    "- Precision: precision = precision_score(true_classes, predicted_classes, average='weighted')\n",
    "- Confusion MAtrix (as Array): conf_matrix = confusion_matrix(true_classes, predicted_classes)\n",
    "- Plot Confusion Matrix: print_conf_matrix(true_classes, predicted_classes,class_names)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "image_size=224\n",
    "channels=3\n",
    "autotune = tf.data.experimental.AUTOTUNE # Adapt preprocessing and prefetching dynamically\n",
    "\n",
    "def data_split(df):\n",
    "    \"\"\"Splits and returns the dataset into training, validation, and test\"\"\"\n",
    "    X_temp, X_test, y_temp, y_test = train_test_split(df['Image_Folder'], df['Label'], test_size=0.15, random_state=42)\n",
    "    X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.176, random_state=42)\n",
    "    #convert labels to array\n",
    "    y_train = np.array(y_train).tolist()\n",
    "    y_val = np.array(y_val).tolist()\n",
    "    y_test = np.array(y_test).tolist()\n",
    "    #print number of observations per datasets\n",
    "    print(\"Nr. Training:\",len(X_train),\"Nr. Validation:\",len(X_val),\"Nr. Test:\",len(X_test))\n",
    "    \n",
    "    return X_train, X_val, X_test, y_train, y_val, y_test\n",
    "\n",
    "\n",
    "def load_image(path):\n",
    "    \"\"\"Load an image from Azure Blob Storage.\"\"\"\n",
    "    blob_client = container_client.get_blob_client(path)\n",
    "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
    "    \n",
    "    return io.BytesIO(blob_data)\n",
    "\n",
    "\n",
    "def load_and_preprocess_image(path):\n",
    "    \"\"\"Loads an image, decodes it to grayscale, resizes, and normalizes it.\"\"\"\n",
    "    # Load image\n",
    "    image_file = load_image(path.numpy().decode('utf-8'))\n",
    "    # Decode the image to grayscale\n",
    "    image_tensor = tf.io.decode_image(image_file.getvalue(), channels=channels)\n",
    "    # Resize the image\n",
    "    image_resized = tf.image.resize(image_tensor, [image_size, image_size])\n",
    "    # Normalize the image data\n",
    "    image_normalized = image_resized / 255.0\n",
    "    return image_normalized\n",
    "\n",
    "\n",
    "def process_tensor(path, label):\n",
    "    \"\"\"Function to load an image from blob storage, decode, resize, and normalize it.\"\"\"\n",
    "    image_normalized = tf.py_function(load_and_preprocess_image, [path], tf.float32)\n",
    "    # Ensure the shape is set correctly for grayscale\n",
    "    image_normalized.set_shape([image_size, image_size, channels])\n",
    "    return image_normalized, label\n",
    "\n",
    "\n",
    "#def create_dataset(filenames, labels, is_training=True):\n",
    "#    \"\"\"Creates a TensorFlow dataset from filenames and labels.\"\"\"\n",
    "#    dataset = tf.data.Dataset.from_tensor_slices((filenames, labels))\n",
    "    dataset = dataset.map(process_tensor, num_parallel_calls=tf.data.AUTOTUNE)\n",
    "    #shuffle the data when it is the training dataset\n",
    "    if is_training:\n",
    "        dataset = dataset.cache()\n",
    "        dataset = dataset.shuffle(buffer_size=1024)\n",
    "    #creates batches    \n",
    "    dataset = dataset.batch(256)\n",
    "    dataset = dataset.prefetch(tf.data.AUTOTUNE)\n",
    "\n",
    "    return dataset\n",
    "\n",
    "\n",
    "def create_all_datasets(X_train, X_val, X_test, y_train, y_val, y_test ):\n",
    "    \"\"\"Creates train, test, and val datasets by calling the create_dataset function each.\"\"\"\n",
    "    train_ds = create_dataset(X_train, y_train)\n",
    "    test_ds = create_dataset(X_test, y_test, False)\n",
    "    val_ds = create_dataset(X_val, y_val, False)\n",
    "    \n",
    "    return train_ds, test_ds, val_ds\n",
    "\n",
    "\n",
    "def print_dataset(dataset):\n",
    "    \"\"\"Print the plain dataset.\"\"\"\n",
    "    for images, labels in dataset.take(1):  # Here, take(1) takes the first batch\n",
    "        print(\"Images:\", images.numpy())  # Convert tensor to numpy array and print\n",
    "        print(\"Labels:\", labels.numpy())  # Convert tensor to numpy array and print\n",
    "\n",
    "\n",
    "def plot_history(model):\n",
    "    \"\"\"Plots the accuracy and loss of the inputted model.\"\"\"\n",
    "    # summarize history for accuracy\n",
    "    plt.plot(model.history['accuracy'])\n",
    "    plt.plot(model.history['val_accuracy'])\n",
    "    plt.title('model accuracy')\n",
    "    plt.ylabel('accuracy')\n",
    "    plt.xlabel('epoch')\n",
    "    plt.legend(['Train', 'Validation'], loc='upper left')\n",
    "    plt.show()\n",
    "    \n",
    "    # summarize history for loss\n",
    "    plt.plot(model.history['loss'])\n",
    "    plt.plot(model.history['val_loss'])\n",
    "    plt.title('model loss')\n",
    "    plt.ylabel('loss')\n",
    "    plt.xlabel('epoch')\n",
    "    plt.legend(['Train', 'Validation'], loc='upper left')\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "def print_predictions(model, ds):\n",
    "    \"\"\"Predictions based on test dataset.\"\"\"\n",
    "    #predict\n",
    "    for images, labels in ds:\n",
    "        predictions = model.predict(images)  # Only pass image data\n",
    "        classes = predictions.argmax(axis=-1) #selects biggest value as prediction\n",
    "\n",
    "        for pred, classe, label in zip(predictions,classes, labels):\n",
    "            print(\"Prediction:\", pred,\"Pred. Class: \",classe, \"Actual Label:\", label.numpy())# Print the first prediction\n",
    "        break\n",
    "    \n",
    "        \n",
    "def plot_model(model): \n",
    "    \"\"\"Plot model with predefined arguments.\"\"\"\n",
    "    plot_model(model, \n",
    "            to_file='vgg.png',\n",
    "            show_shapes=True,\n",
    "            show_dtype=True,\n",
    "            show_layer_names=True,\n",
    "            show_layer_activations=True,\n",
    "            show_trainable=False)\n",
    "    \n",
    "\n",
    "def evaluate_model(model, test_ds):\n",
    "    result = model.evaluate(test_ds)\n",
    "    # Assuming accuracy was the second metric (index 1), extract the accuracy.\n",
    "    test_accuracy = result[1] * 100  # Convert to percentage\n",
    "    print(f\"Test Accuracy: {test_accuracy:.2f}%\")\n",
    "    return test_accuracy\n",
    "\n",
    "\n",
    "def true_pred_classes(model, dataset): \n",
    "    \"\"\"\n",
    "    Evaluates the given model using the dataset.\n",
    "    Returns: accuracy, f1, recall, precision, confusion matrix\n",
    "    \"\"\"\n",
    "    # Collect all labels and predictions\n",
    "    true_classes = []\n",
    "    predicted_classes = []\n",
    "\n",
    "    # Iterate over the dataset\n",
    "    for images, labels in dataset:\n",
    "        # Predict batch\n",
    "        preds = model.predict(images)\n",
    "        preds = np.argmax(preds, axis=1)\n",
    "        true = labels.numpy()  # Assuming labels are already integer-encoded\n",
    "\n",
    "        # Append to lists\n",
    "        true_classes.extend(true)\n",
    "        predicted_classes.extend(preds)\n",
    "    return true_classes,predicted_classes\n",
    "\n",
    "\n",
    "def print_conf_matrix(true_classes, predicted_classes, class_names):\n",
    "    \"\"\"\n",
    "    Print confusion matrix.\n",
    "    \"\"\"\n",
    "    conf_matrix = confusion_matrix(true_classes, predicted_classes)\n",
    "    df_cm = pd.DataFrame(\n",
    "        conf_matrix, index=class_names, columns=class_names,\n",
    "    )\n",
    "    fig = plt.figure(figsize=(10,7))\n",
    "    heatmap = sns.heatmap(df_cm, annot=True, fmt=\"d\", cmap='Blues')\n",
    "\n",
    "    # Set aesthetics for better readability\n",
    "    heatmap.yaxis.set_ticklabels(heatmap.yaxis.get_ticklabels(), rotation=0, ha='right', fontsize=14)\n",
    "    heatmap.xaxis.set_ticklabels(heatmap.xaxis.get_ticklabels(), rotation=45, ha='right', fontsize=14)\n",
    "\n",
    "    plt.ylabel('True label')\n",
    "    plt.xlabel('Predicted label')\n",
    "    plt.title('Confusion Matrix')\n",
    "    plt.show()\n",
    "\n",
    "#def upload_model_to_azure(model, model_name):\n",
    "    # Save the model locally\n",
    "    #local_model_path = f\"{model_name}.keras\"\n",
    "    #model.save(local_model_path)\n",
    "    \n",
    "    # Get the blob client\n",
    "    #blob_client = blob_service_client.get_blob_client(container='meterml', blob=f'models/{model_name}.keras')\n",
    "    \n",
    "    # Upload the model file to Azure Blob Storage\n",
    "    #with open(local_model_path, 'rb') as data:\n",
    "    #    blob_client.upload_blob(data, overwrite=True)\n",
    "    \n",
    "    # Optionally, delete the local model file after upload\n",
    "    #os.remove(local_model_path)\n",
    "    \n",
    "    #print(\"Model successfully stored in Azure.\")\n",
    "\n",
    "\n",
    "#def download_model_from_azure(model_name):\n",
    "    # Construct the blob path\n",
    " #   blob_path = f'models/{model_name}.keras'\n",
    "  #  blob_client = blob_service_client.get_blob_client(container='meterml', blob=blob_path)\n",
    "    \n",
    "   # try:\n",
    "    #    # Download the blob to a temporary file\n",
    "     #   with tempfile.NamedTemporaryFile(delete=False, suffix='.keras') as temp_file:\n",
    "      #      temp_file.write(blob_client.download_blob().readall())\n",
    "       #     temp_file_path = temp_file.name\n",
    "\n",
    "        # Load the model using TensorFlow Keras\n",
    "        #model = tf.keras.models.load_model(temp_file_path)\n",
    "        \n",
    "   # except ResourceNotFoundError:\n",
    "    #    print(f\"Error: The model '{model_name}' was not found in Azure Blob Storage.\")\n",
    "    #    return None\n",
    "    #except Exception as e:\n",
    "    #    print(f\"An error occurred while loading the model: {e}\")\n",
    "    #    return None\n",
    "    #finally:\n",
    "    #    if 'temp_file_path' in locals():\n",
    "            # Optionally, delete the temporary file\n",
    "    #        os.remove(temp_file_path)\n",
    "\n",
    "    #print(\"Model loaded. Enter model.summary() to print a model summary.\")\n",
    "    #return model"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Connect to Azure"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "#set up storage\n",
    "#connection_string = \"DefaultEndpointsProtocol=https;AccountName=mlfinalexam5505462853;AccountKey=0c40lghglG5/GlNK9yujDQAgo38GKoS2I3DeC/g22hwAEIFANKpmC/TqOpRk4RCT1DbfNiHBFt72+AStB+PfUA==;EndpointSuffix=core.windows.net\"\n",
    "#container_name = \"meterml\"\n",
    "\n",
    "#create client\n",
    "#blob_service_client = BlobServiceClient.from_connection_string(connection_string)\n",
    "#container_client = blob_service_client.get_container_client(container_name)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Load Image Paths and Labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "#get filepaths\n",
    "df_train = pd.read_csv(\"FINAL_METER_ML_train_model.csv\")\n",
    "df_val = pd.read_csv(\"FINAL_METER_ML_val.csv\")\n",
    "df_test = pd.read_csv(\"FINAL_METER_ML_test.csv\")\n",
    "\n",
    "\n",
    "# convert each string in the DataFrame to a list\n",
    "df_train['Label'] = df_train['Label'].apply(ast.literal_eval).apply(np.array)\n",
    "df_val['Label'] = df_val['Label'].apply(ast.literal_eval).apply(np.array)\n",
    "df_test['Label'] = df_test['Label'].apply(ast.literal_eval).apply(np.array)\n",
    "\n",
    "\n",
    "# convert each list in the DataFrame to a numpy array\n",
    "#df['Label'] = df['Label'].apply(np.array)\n",
    "\n",
    "class_names=[\"CAFOs\",\"Landfills\",\"Mines\",\"Negative\",\"ProcessingPlants\",\"RefineriesAndTerminals\",\"WWTreatment\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "y_train = np.array(df_train['Label'].tolist())\n",
    "y_val = np.array(df_val['Label'].tolist())\n",
    "y_test = np.array(df_test['Label'].tolist())\n",
    "\n",
    "X_val = np.load(\"x_val.npy\")\n",
    "X_test = np.load(\"x_test.npy\")\n",
    "X_train = np.load(\"x_train.npy\")\n",
    "\n",
    "def create_labels(labels):\n",
    "    y_labels=[]\n",
    "    for label in labels:\n",
    "        y_labels.append(label)\n",
    "    y_label = np.array(y_labels)\n",
    "    return y_label\n",
    "\n",
    "#create labels \n",
    "y_val = create_labels(y_val)\n",
    "y_test = create_labels(y_test)\n",
    "y_train = create_labels(y_train)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train = df_train['Image_Folder']\n",
    "X_test = df_test['Image_Folder']\n",
    "X_val= df_val['Image_Folder']\n",
    "\n",
    "y_train = np.array(df_train['Label']).tolist()\n",
    "y_val = np.array(df_val['Label']).tolist()\n",
    "y_test = np.array(df_test['Label']).tolist()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Create Datasets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_ds, test_ds, val_ds = create_all_datasets(X_train, X_val, X_test, y_train, y_val, y_test)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Models"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Alexnet New"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/30\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/ucloud/.local/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.\n",
      "  super().__init__(activity_regularizer=activity_regularizer, **kwargs)\n",
      "2024-05-14 22:26:29.498443: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:450] ShuffleDatasetV3:3: Filling up shuffle buffer (this may take a while): 204 of 1024\n",
      "2024-05-14 22:26:41.712451: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:450] ShuffleDatasetV3:3: Filling up shuffle buffer (this may take a while): 414 of 1024\n",
      "2024-05-14 22:26:59.507360: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:450] ShuffleDatasetV3:3: Filling up shuffle buffer (this may take a while): 860 of 1024\n",
      "2024-05-14 22:27:08.518141: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:480] Shuffle buffer filled.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m1870s\u001b[0m 11s/step - accuracy: 0.7217 - loss: 3347.1370 - val_accuracy: 0.0990 - val_loss: 4.4185 - learning_rate: 0.0010\n",
      "Epoch 2/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m386s\u001b[0m 2s/step - accuracy: 0.5846 - loss: 1.4751 - val_accuracy: 0.0990 - val_loss: 13.4518 - learning_rate: 0.0010\n",
      "Epoch 3/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m386s\u001b[0m 2s/step - accuracy: 0.6081 - loss: 2.1781 - val_accuracy: 0.0990 - val_loss: 4.7968 - learning_rate: 0.0010\n",
      "Epoch 4/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m387s\u001b[0m 2s/step - accuracy: 0.5778 - loss: 1.6014 - val_accuracy: 0.0990 - val_loss: 2.7679 - learning_rate: 0.0010\n",
      "Epoch 5/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m387s\u001b[0m 2s/step - accuracy: 0.4859 - loss: 1.7331 - val_accuracy: 0.0752 - val_loss: 2.3904 - learning_rate: 0.0010\n",
      "Epoch 6/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m388s\u001b[0m 2s/step - accuracy: 0.4984 - loss: 1.4515 - val_accuracy: 0.0990 - val_loss: 5.0468 - learning_rate: 0.0010\n",
      "Epoch 7/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m387s\u001b[0m 2s/step - accuracy: 0.3592 - loss: 1.9335 - val_accuracy: 0.0752 - val_loss: 2.3753 - learning_rate: 0.0010\n",
      "Epoch 8/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m386s\u001b[0m 2s/step - accuracy: 0.1976 - loss: 1.9034 - val_accuracy: 0.0990 - val_loss: 7.9339 - learning_rate: 0.0010\n",
      "Epoch 9/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m388s\u001b[0m 2s/step - accuracy: 0.5392 - loss: 1.8385 - val_accuracy: 0.0990 - val_loss: 3.9598 - learning_rate: 0.0010\n",
      "Epoch 10/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m387s\u001b[0m 2s/step - accuracy: 0.2035 - loss: 2.2675 - val_accuracy: 0.0752 - val_loss: 2.9508 - learning_rate: 0.0010\n",
      "Epoch 11/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m386s\u001b[0m 2s/step - accuracy: 0.3616 - loss: 1.9613 - val_accuracy: 0.0752 - val_loss: 2.1825 - learning_rate: 0.0010\n",
      "Epoch 12/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m388s\u001b[0m 2s/step - accuracy: 0.3955 - loss: 1.6901 - val_accuracy: 0.0990 - val_loss: 2.5301 - learning_rate: 0.0010\n",
      "Epoch 13/30\n",
      "\u001b[1m165/165\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 2s/step - accuracy: 0.3720 - loss: 1.6522"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-05-15 00:14:36.568856: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:a3ccb3c7-d01e-007d-694c-a63535000000\n",
      "Time:2024-05-14T22:14:36.4966508Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:a3ccb3c7-d01e-007d-694c-a63535000000\n",
      "Time:2024-05-14T22:14:36.4966508Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:a3ccb3c7-d01e-007d-694c-a63535000000\n",
      "Time:2024-05-14T22:14:36.4966508Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:a3ccb3c7-d01e-007d-694c-a63535000000\n",
      "Time:2024-05-14T22:14:36.4966508Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.570716: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:71e6cb6b-e01e-0082-7f4c-a605a8000000\n",
      "Time:2024-05-14T22:14:36.5200479Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:71e6cb6b-e01e-0082-7f4c-a605a8000000\n",
      "Time:2024-05-14T22:14:36.5200479Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:71e6cb6b-e01e-0082-7f4c-a605a8000000\n",
      "Time:2024-05-14T22:14:36.5200479Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:71e6cb6b-e01e-0082-7f4c-a605a8000000\n",
      "Time:2024-05-14T22:14:36.5200479Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.573162: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:daf27f39-701e-00af-254c-a6b6db000000\n",
      "Time:2024-05-14T22:14:36.5332422Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:daf27f39-701e-00af-254c-a6b6db000000\n",
      "Time:2024-05-14T22:14:36.5332422Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:daf27f39-701e-00af-254c-a6b6db000000\n",
      "Time:2024-05-14T22:14:36.5332422Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:daf27f39-701e-00af-254c-a6b6db000000\n",
      "Time:2024-05-14T22:14:36.5332422Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.605902: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:3e47b212-c01e-0071-3f4c-a6a23d000000\n",
      "Time:2024-05-14T22:14:36.5448260Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:3e47b212-c01e-0071-3f4c-a6a23d000000\n",
      "Time:2024-05-14T22:14:36.5448260Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:3e47b212-c01e-0071-3f4c-a6a23d000000\n",
      "Time:2024-05-14T22:14:36.5448260Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:3e47b212-c01e-0071-3f4c-a6a23d000000\n",
      "Time:2024-05-14T22:14:36.5448260Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.621123: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:f8867621-401e-009b-4c4c-a68513000000\n",
      "Time:2024-05-14T22:14:36.4825491Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:f8867621-401e-009b-4c4c-a68513000000\n",
      "Time:2024-05-14T22:14:36.4825491Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:f8867621-401e-009b-4c4c-a68513000000\n",
      "Time:2024-05-14T22:14:36.4825491Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:f8867621-401e-009b-4c4c-a68513000000\n",
      "Time:2024-05-14T22:14:36.4825491Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.629469: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:ad470f5a-501e-0001-614c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.5647510Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ad470f5a-501e-0001-614c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.5647510Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:ad470f5a-501e-0001-614c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.5647510Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ad470f5a-501e-0001-614c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.5647510Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.631150: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\n",
      "Time:2024-05-14T22:14:36.5634377Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\n",
      "Time:2024-05-14T22:14:36.5634377Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\n",
      "Time:2024-05-14T22:14:36.5634377Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\n",
      "Time:2024-05-14T22:14:36.5634377Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.633830: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:fccce35e-701e-005b-214c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.5559628Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:fccce35e-701e-005b-214c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.5559628Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:fccce35e-701e-005b-214c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.5559628Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:fccce35e-701e-005b-214c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.5559628Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.655560: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:bd371205-301e-004a-7e4c-a6e799000000\n",
      "Time:2024-05-14T22:14:36.5534219Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:bd371205-301e-004a-7e4c-a6e799000000\n",
      "Time:2024-05-14T22:14:36.5534219Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:bd371205-301e-004a-7e4c-a6e799000000\n",
      "Time:2024-05-14T22:14:36.5534219Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:bd371205-301e-004a-7e4c-a6e799000000\n",
      "Time:2024-05-14T22:14:36.5534219Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.669403: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:57d9e95e-401e-0040-674c-a6432e000000\n",
      "Time:2024-05-14T22:14:36.5577195Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:57d9e95e-401e-0040-674c-a6432e000000\n",
      "Time:2024-05-14T22:14:36.5577195Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:57d9e95e-401e-0040-674c-a6432e000000\n",
      "Time:2024-05-14T22:14:36.5577195Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:57d9e95e-401e-0040-674c-a6432e000000\n",
      "Time:2024-05-14T22:14:36.5577195Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.671584: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:348f1cca-101e-004d-404c-a68bfa000000\n",
      "Time:2024-05-14T22:14:36.5353096Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:348f1cca-101e-004d-404c-a68bfa000000\n",
      "Time:2024-05-14T22:14:36.5353096Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:348f1cca-101e-004d-404c-a68bfa000000\n",
      "Time:2024-05-14T22:14:36.5353096Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:348f1cca-101e-004d-404c-a68bfa000000\n",
      "Time:2024-05-14T22:14:36.5353096Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.675135: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:e2718cd7-301e-0028-304c-a625be000000\n",
      "Time:2024-05-14T22:14:36.5413880Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:e2718cd7-301e-0028-304c-a625be000000\n",
      "Time:2024-05-14T22:14:36.5413880Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:e2718cd7-301e-0028-304c-a625be000000\n",
      "Time:2024-05-14T22:14:36.5413880Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:e2718cd7-301e-0028-304c-a625be000000\n",
      "Time:2024-05-14T22:14:36.5413880Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.682691: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf64c2-b01e-008f-364c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.6373884Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf64c2-b01e-008f-364c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.6373884Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf64c2-b01e-008f-364c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.6373884Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf64c2-b01e-008f-364c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.6373884Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.700694: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf649a-b01e-008f-114c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.5675119Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf649a-b01e-008f-114c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.5675119Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf649a-b01e-008f-114c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.5675119Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf649a-b01e-008f-114c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.5675119Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.702173: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:ad470f7d-501e-0001-804c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.6420725Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ad470f7d-501e-0001-804c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.6420725Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:ad470f7d-501e-0001-804c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.6420725Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ad470f7d-501e-0001-804c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.6420725Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.703857: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:626d1b1f-b01e-0026-534c-a60c0e000000\n",
      "Time:2024-05-14T22:14:36.6091577Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:626d1b1f-b01e-0026-534c-a60c0e000000\n",
      "Time:2024-05-14T22:14:36.6091577Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:626d1b1f-b01e-0026-534c-a60c0e000000\n",
      "Time:2024-05-14T22:14:36.6091577Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:626d1b1f-b01e-0026-534c-a60c0e000000\n",
      "Time:2024-05-14T22:14:36.6091577Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.705240: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:8465e9cb-c01e-005e-5a4c-a6aff6000000\n",
      "Time:2024-05-14T22:14:36.5605262Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:8465e9cb-c01e-005e-5a4c-a6aff6000000\n",
      "Time:2024-05-14T22:14:36.5605262Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:8465e9cb-c01e-005e-5a4c-a6aff6000000\n",
      "Time:2024-05-14T22:14:36.5605262Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:8465e9cb-c01e-005e-5a4c-a6aff6000000\n",
      "Time:2024-05-14T22:14:36.5605262Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.707785: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf64d3-b01e-008f-474c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.6719486Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf64d3-b01e-008f-474c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.6719486Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf64d3-b01e-008f-474c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.6719486Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf64d3-b01e-008f-474c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.6719486Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.716782: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:79b01779-c01e-0013-364c-a6601a000000\n",
      "Time:2024-05-14T22:14:36.6583723Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:79b01779-c01e-0013-364c-a6601a000000\n",
      "Time:2024-05-14T22:14:36.6583723Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:79b01779-c01e-0013-364c-a6601a000000\n",
      "Time:2024-05-14T22:14:36.6583723Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:79b01779-c01e-0013-364c-a6601a000000\n",
      "Time:2024-05-14T22:14:36.6583723Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.717206: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\n",
      "Time:2024-05-14T22:14:36.5634377Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\n",
      "Time:2024-05-14T22:14:36.5634377Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\n",
      "Time:2024-05-14T22:14:36.5634377Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\n",
      "Time:2024-05-14T22:14:36.5634377Z</Message></Error>\n",
      "\n",
      "\n",
      "\t [[{{node EagerPyFunc}}]]\n",
      "\t [[IteratorGetNext]]\n",
      "2024-05-15 00:14:36.718458: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:fccce3c3-701e-005b-044c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.6569437Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:fccce3c3-701e-005b-044c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.6569437Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:fccce3c3-701e-005b-044c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.6569437Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:fccce3c3-701e-005b-044c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.6569437Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.747383: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf64e7-b01e-008f-5a4c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.7082569Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf64e7-b01e-008f-5a4c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.7082569Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf64e7-b01e-008f-5a4c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.7082569Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf64e7-b01e-008f-5a4c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.7082569Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.761223: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:8465e9dc-c01e-005e-694c-a6aff6000000\n",
      "Time:2024-05-14T22:14:36.6464678Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:8465e9dc-c01e-005e-694c-a6aff6000000\n",
      "Time:2024-05-14T22:14:36.6464678Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:8465e9dc-c01e-005e-694c-a6aff6000000\n",
      "Time:2024-05-14T22:14:36.6464678Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:8465e9dc-c01e-005e-694c-a6aff6000000\n",
      "Time:2024-05-14T22:14:36.6464678Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.769239: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:bd37121c-301e-004a-124c-a6e799000000\n",
      "Time:2024-05-14T22:14:36.7010847Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:bd37121c-301e-004a-124c-a6e799000000\n",
      "Time:2024-05-14T22:14:36.7010847Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:bd37121c-301e-004a-124c-a6e799000000\n",
      "Time:2024-05-14T22:14:36.7010847Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:bd37121c-301e-004a-124c-a6e799000000\n",
      "Time:2024-05-14T22:14:36.7010847Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.776152: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:79b01785-c01e-0013-3f4c-a6601a000000\n",
      "Time:2024-05-14T22:14:36.6961516Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:79b01785-c01e-0013-3f4c-a6601a000000\n",
      "Time:2024-05-14T22:14:36.6961516Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:79b01785-c01e-0013-3f4c-a6601a000000\n",
      "Time:2024-05-14T22:14:36.6961516Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:79b01785-c01e-0013-3f4c-a6601a000000\n",
      "Time:2024-05-14T22:14:36.6961516Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.792367: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:ad470fa2-501e-0001-244c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.7299161Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ad470fa2-501e-0001-244c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.7299161Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:ad470fa2-501e-0001-244c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.7299161Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ad470fa2-501e-0001-244c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.7299161Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.799278: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:fccce3f0-701e-005b-304c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.7186185Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:fccce3f0-701e-005b-304c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.7186185Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:fccce3f0-701e-005b-304c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.7186185Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:fccce3f0-701e-005b-304c-a67d2d000000\n",
      "Time:2024-05-14T22:14:36.7186185Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.800897: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:ad470f92-501e-0001-144c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.6906900Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ad470f92-501e-0001-144c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.6906900Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:ad470f92-501e-0001-144c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.6906900Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:ad470f92-501e-0001-144c-a61bca000000\n",
      "Time:2024-05-14T22:14:36.6906900Z</Message></Error>\n",
      "\n",
      "\n",
      "2024-05-15 00:14:36.805214: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf6501-b01e-008f-734c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.7687292Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf6501-b01e-008f-734c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.7687292Z</Message></Error>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n",
      "    return func(device, token, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n",
      "    ret = self._func(*args)\n",
      "          ^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n",
      "    image_file = load_image(path.numpy().decode('utf-8'))\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n",
      "    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n",
      "    return StorageStreamDownloader(**options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n",
      "    self._response = self._initial_request()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n",
      "    process_storage_error(error)\n",
      "\n",
      "  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n",
      "    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\n",
      "  File \"<string>\", line 1, in <module>\n",
      "\n",
      "azure.core.exceptions.HttpResponseError: The specified account is disabled.\n",
      "RequestId:b6cf6501-b01e-008f-734c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.7687292Z\n",
      "ErrorCode:AccountIsDisabled\n",
      "Content: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\n",
      "RequestId:b6cf6501-b01e-008f-734c-a6cd7c000000\n",
      "Time:2024-05-14T22:14:36.7687292Z</Message></Error>\n",
      "\n",
      "\n"
     ]
    },
    {
     "ename": "UnknownError",
     "evalue": "Graph execution error:\n\nDetected at node EagerPyFunc defined at (most recent call last):\n<stack traces unavailable>\nHttpResponseError: The specified account is disabled.\nRequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\nTime:2024-05-14T22:14:36.5634377Z\nErrorCode:AccountIsDisabled\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\nRequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\nTime:2024-05-14T22:14:36.5634377Z</Message></Error>\nTraceback (most recent call last):\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n    return func(device, token, args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n    outputs = self._call(device, args)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n    ret = self._func(*args)\n          ^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n    image_file = load_image(path.numpy().decode('utf-8'))\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n    return StorageStreamDownloader(**options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n    self._response = self._initial_request()\n                     ^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n    process_storage_error(error)\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"<string>\", line 1, in <module>\n\nazure.core.exceptions.HttpResponseError: The specified account is disabled.\nRequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\nTime:2024-05-14T22:14:36.5634377Z\nErrorCode:AccountIsDisabled\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\nRequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\nTime:2024-05-14T22:14:36.5634377Z</Message></Error>\n\n\n\t [[{{node EagerPyFunc}}]]\n\t [[IteratorGetNext]] [Op:__inference_one_step_on_iterator_425499]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnknownError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[10], line 53\u001b[0m\n\u001b[1;32m     50\u001b[0m t0\u001b[38;5;241m=\u001b[39mtime\u001b[38;5;241m.\u001b[39mtime()\n\u001b[1;32m     52\u001b[0m \u001b[38;5;66;03m# Fit model and save history for further analysis:\u001b[39;00m\n\u001b[0;32m---> 53\u001b[0m history \u001b[38;5;241m=\u001b[39m \u001b[43malexnet\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrain_ds\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     54\u001b[0m \u001b[43m                      \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mval_ds\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\n\u001b[1;32m     55\u001b[0m \u001b[43m                      \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m30\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m     56\u001b[0m \u001b[43m                      \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m128\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m     57\u001b[0m \u001b[43m                      \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m[\u001b[49m\u001b[43mtf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mkeras\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mEarlyStopping\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpatience\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mkeras\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mReduceLROnPlateau\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpatience\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     59\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTraining time in seconds:\u001b[39m\u001b[38;5;124m\"\u001b[39m, time\u001b[38;5;241m.\u001b[39mtime()\u001b[38;5;241m-\u001b[39mt0)\n\u001b[1;32m     61\u001b[0m \u001b[38;5;66;03m#save model\u001b[39;00m\n",
      "File \u001b[0;32m~/.local/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py:122\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    119\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m    121\u001b[0m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m--> 122\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    124\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/.local/lib/python3.12/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mUnknownError\u001b[0m: Graph execution error:\n\nDetected at node EagerPyFunc defined at (most recent call last):\n<stack traces unavailable>\nHttpResponseError: The specified account is disabled.\nRequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\nTime:2024-05-14T22:14:36.5634377Z\nErrorCode:AccountIsDisabled\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\nRequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\nTime:2024-05-14T22:14:36.5634377Z</Message></Error>\nTraceback (most recent call last):\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 268, in __call__\n    return func(device, token, args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 146, in __call__\n    outputs = self._call(device, args)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/ops/script_ops.py\", line 153, in _call\n    ret = self._func(*args)\n          ^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/tmp/ipykernel_667/2464947377.py\", line 30, in load_and_preprocess_image\n    image_file = load_image(path.numpy().decode('utf-8'))\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/tmp/ipykernel_667/2464947377.py\", line 22, in load_image\n    blob_data = blob_client.download_blob().readall()  # Directly read all bytes\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/core/tracing/decorator.py\", line 78, in wrapper_use_tracer\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_client.py\", line 952, in download_blob\n    return StorageStreamDownloader(**options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 367, in __init__\n    self._response = self._initial_request()\n                     ^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_download.py\", line 463, in _initial_request\n    process_storage_error(error)\n\n  File \"/home/ucloud/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/response_handlers.py\", line 182, in process_storage_error\n    exec(\"raise error from None\")   # pylint: disable=exec-used # nosec\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File \"<string>\", line 1, in <module>\n\nazure.core.exceptions.HttpResponseError: The specified account is disabled.\nRequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\nTime:2024-05-14T22:14:36.5634377Z\nErrorCode:AccountIsDisabled\nContent: <?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.\nRequestId:0fc1844a-901e-007c-4f4c-a66ae9000000\nTime:2024-05-14T22:14:36.5634377Z</Message></Error>\n\n\n\t [[{{node EagerPyFunc}}]]\n\t [[IteratorGetNext]] [Op:__inference_one_step_on_iterator_425499]"
     ]
    }
   ],
   "source": [
    "IMG_SIZE = 224\n",
    "CHANNELS = 3\n",
    "\n",
    "alexnet = Sequential()\n",
    "\n",
    "alexnet.add(Conv2D(96, kernel_size=(11,11), strides= 4,\n",
    "                        padding= 'valid', activation= 'relu',\n",
    "                        input_shape= (224,224,3),\n",
    "                        kernel_initializer= 'he_normal'))\n",
    "\n",
    "alexnet.add(MaxPooling2D(pool_size=(3,3), strides= (2,2),\n",
    "                              padding= 'valid', data_format= None))\n",
    "\n",
    "alexnet.add(Conv2D(256, kernel_size=(5,5), strides= 1,\n",
    "                        padding= 'same', activation= 'relu',\n",
    "                        kernel_initializer= 'he_normal'))\n",
    "                        \n",
    "alexnet.add(MaxPooling2D(pool_size=(3,3), strides= (2,2),\n",
    "                              padding= 'valid', data_format= None)) \n",
    "\n",
    "alexnet.add(Conv2D(384, kernel_size=(3,3), strides= 1,\n",
    "                        padding= 'same', activation= 'relu',\n",
    "                        kernel_initializer= 'he_normal'))\n",
    "\n",
    "alexnet.add(Conv2D(384, kernel_size=(3,3), strides= 1,\n",
    "                        padding= 'same', activation= 'relu',\n",
    "                        kernel_initializer= 'he_normal'))\n",
    "\n",
    "alexnet.add(Conv2D(256, kernel_size=(3,3), strides= 1,\n",
    "                        padding= 'same', activation= 'relu',\n",
    "                        kernel_initializer= 'he_normal'))\n",
    "\n",
    "alexnet.add(MaxPooling2D(pool_size=(3,3), strides= (2,2),\n",
    "                        padding= 'valid', data_format= None))\n",
    "\n",
    "alexnet.add(Flatten())\n",
    "alexnet.add(Dense(4096, activation= 'relu'))\n",
    "alexnet.add(Dense(4096, activation= 'relu'))\n",
    "\n",
    "#Output layer with 7 classes insteas of 1000 as in model architecture:\n",
    "alexnet.add(Dense(7, activation= 'softmax'))\n",
    "\n",
    "\n",
    "# Compile the model:\n",
    "alexnet.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),\n",
    "                loss=tf.keras.losses.CategoricalCrossentropy(),\n",
    "                metrics=['accuracy'])\n",
    "\n",
    "#initialize timing\n",
    "t0=time.time()\n",
    "\n",
    "# Fit model and save history for further analysis:\n",
    "history = alexnet.fit(X_train,\n",
    "                      y_train,\n",
    "                      validation_data = (X_val, y_val), \n",
    "                      epochs=30,\n",
    "                      batch_size=128,\n",
    "                      callbacks=[tf.keras.callbacks.EarlyStopping(patience=5), tf.keras.callbacks.ReduceLROnPlateau(patience=5)])\n",
    "\n",
    "print(\"Training time in seconds:\", time.time()-t0)\n",
    "\n",
    "#save model\n",
    "alexnet.save('alexnet.keras')\n",
    "\n",
    "#Upload model to azure:\n",
    "#upload_model_to_azure(alexnet, 'alexnet.keras')\n",
    "\n",
    "plot_history(history)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Self-trained VGG16\n",
    "Source: https://medium.com/@siddheshb008/vgg-net-architecture-explained-71179310050f"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Set Variables\n",
    "epochs = 50\n",
    "batch_size = 128\n",
    "\n",
    "# Define Model\n",
    "_input = Input((224,224,3)) \n",
    "\n",
    "conv1  = Conv2D(filters=64, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(_input)\n",
    "conv2  = Conv2D(filters=64, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(conv1)\n",
    "pool1  = MaxPooling2D((2, 2))(conv2)\n",
    "\n",
    "conv3  = Conv2D(filters=128, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(pool1)\n",
    "conv4  = Conv2D(filters=128, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(conv3)\n",
    "pool2  = MaxPooling2D((2, 2))(conv4)\n",
    "\n",
    "conv5  = Conv2D(filters=256, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(pool2)\n",
    "conv6  = Conv2D(filters=256, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(conv5)\n",
    "conv7  = Conv2D(filters=256, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(conv6)\n",
    "pool3  = MaxPooling2D((2, 2))(conv7)\n",
    "\n",
    "conv8  = Conv2D(filters=512, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(pool3)\n",
    "conv9  = Conv2D(filters=512, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(conv8)\n",
    "conv10 = Conv2D(filters=512, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(conv9)\n",
    "pool4  = MaxPooling2D((2, 2))(conv10)\n",
    "\n",
    "conv11 = Conv2D(filters=512, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(pool4)\n",
    "conv12 = Conv2D(filters=512, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(conv11)\n",
    "conv13 = Conv2D(filters=512, kernel_size=(3,3), padding=\"same\", activation=\"relu\")(conv12)\n",
    "pool5  = MaxPooling2D((2, 2))(conv13)\n",
    "\n",
    "flat   = Flatten()(pool5)\n",
    "dense1 = Dense(4096, activation=\"relu\")(flat)\n",
    "dense2 = Dense(4096, activation=\"relu\")(dense1)\n",
    "output = Dense(7, activation=\"softmax\")(dense2) #adapted number of outputs and outputfunction\n",
    "\n",
    "vgg16_model  = Model(inputs=_input, outputs=output)\n",
    "\n",
    "\n",
    "#compile the model\n",
    "vgg16_model.compile(optimizer=tf.keras.optimizers.Adam(),\n",
    "              loss=tf.keras.losses.CategoricalCrossentropy(),\n",
    "              metrics=['accuracy'])\n",
    "\n",
    "##provide a model summary\n",
    "vgg16_model.summary()\n",
    "\n",
    "#initialize timing\n",
    "t0=time.time()\n",
    "\n",
    "#fit the model\n",
    "vgg16_model.fit(\n",
    "    X_train,\n",
    "    y_train,\n",
    "    validation_data = (X_val, y_val),\n",
    "    epochs=epochs,\n",
    "    batch_size=batch_size,\n",
    "    callbacks = [ReduceLROnPlateau(patience=5), EarlyStopping(patience=5)])\n",
    "\n",
    "t1=time.time()\n",
    "print(\"Training time in seconds:\", t1-t0)\n",
    "\n",
    "# save model:\n",
    "vgg16_model.save(\"vgg16_model.keras\")\n",
    "\n",
    "# upload azure:\n",
    "#upload_model_to_azure(vgg16_model, \"vgg16_model.keras\")\n",
    "\n",
    "#Plot history\n",
    "plot_history(vgg16_model)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
